# docker compose up

version: "3.1"

services:
  app:
    build: .
    container_name: ottai-nightscout-uploader
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      OTTAI_BASE_URL:
      OTTAI_TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg0MDA1NDMsInVzZXJJZCI6IjIwMTg3MzY0In0.zB78VhTLwIyqGCGM07E_5Nf0ttyIwfDr-sqf0d6uT88ufdtNKGxbhh6ELuJIIyGgNwwnNx4UqxGmUbEYaPsQKg
      NS_URL:
      NS_API_SECRET:
      HOURS_AGO: 5
      NS_URL__user049395: https://j30256707.nightscout-jino.ru
      NS_SECRET__user049395: 5be8BbfFcyC8
    command: python -u main.py